//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPPRAKTIKA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public string login { get; set; }
        public string password { get; set; }
        public int КодПользователя { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public Nullable<bool> Admin { get; set; }
        public string ОтветНаВопрос { get; set; }
    }
}
