//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPPRAKTIKA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Доход
    {
        public int КодДохода { get; set; }
        public Nullable<int> КодСотрудника { get; set; }
        public string ВидДохода { get; set; }
        public Nullable<decimal> СуммаДохода { get; set; }
    
        public virtual Сотрудник Сотрудник { get; set; }
    }
}
