//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPPRAKTIKA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сотрудник
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Сотрудник()
        {
            this.Доход = new HashSet<Доход>();
            this.Счёт = new HashSet<Счёт>();
        }
    
        public int КодСотрудника { get; set; }
        public string Имя { get; set; }
        public string Фамилия { get; set; }
        public string Отчество { get; set; }
        public Nullable<int> НомерДоговора { get; set; }
        public string Телефон { get; set; }
        public Nullable<System.DateTime> ДатаРождения { get; set; }
        public Nullable<int> НомерСчёта { get; set; }
        public Nullable<int> КодДолжности { get; set; }
        public string ЭлектроннаяПочта { get; set; }
    
        public virtual Договор Договор { get; set; }
        public virtual Должность Должность { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Доход> Доход { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Счёт> Счёт { get; set; }
    }
}
