//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPPRAKTIKA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Счёт
    {
        public int НомерСчёта { get; set; }
        public string Валюта { get; set; }
        public Nullable<int> КодСотрудника { get; set; }
        public Nullable<decimal> СуммаСчёта { get; set; }
        public Nullable<int> НомерДоговора { get; set; }
    
        public virtual Договор Договор { get; set; }
        public virtual Сотрудник Сотрудник { get; set; }
    }
}
